In [2]:
import pandas as pd
import numpy as  sp
import scipy as sp
import seaborn as sns
import matplotlib.pyplot as   plt

In [3]:
import os

In [13]:
df =pd.read_csv(r"D:\Pharma analyse\pediatrieCon.csv")

In [14]:
df

,cEVT_ID,cEVT_Date,cCHP_VAL_Alpha,cCHP_VAL_Num,cCHP_VAL_Memo,cCHP_Code,NOM COMPLET,cPAT_Genre,DNN,ANNE,AGE,<= 5ans
0,1445d354-842a-4e34-868b-870115d1ffe1,45096.63206,NaN,NaN,1erF son frère en BSA\ntransfusion + 1x pathol...,PRM2_Antecedant,USHINDI MUBAKE,M,2020/08/27,2020,4,OUI
1,5d53b8de-e964-4077-8093-4af43e947179,45038.45898,NaN,NaN,5eme sur 5 accouche par césarienne pour micros...,PRM2_Antecedant,MIHIYO MUTEBERWA,M,2022/10/25,2022,2,OUI
2,be99614c-e73f-4eee-8915-81394435aa95,45030.50928,NaN,NaN,"Drépanocytaire connu ,suivi à l’HPNK, sous hy...",PRM2_Antecedant,KAOTA KAOMBO micheline,F,2010/11/15,2010,14,NON
3,b19d4859-ff8a-4f98-8399-b61d6ffb75f1,44932.42413,CUSTOM,1.0,myocardiopathie acquise ?,DIAG_Synd_2,MWANZE JOANA,F,2009/10/03,2009,15,NON
4,882ea33e-61b4-4688-80fd-0e8a0dea6757,45077.43109,CUSTOM,1.0,cardiopathie,DIAG_Synd_1,RIZIKI NKUNDWANDIHO LILIANE,F,2012/03/05,2012,12,NON
...,...,...,...,...,...,...,...,...,...,...,...,...
114,737a0c45-e9ea-4a95-8ecd-99d1a5837c07,45227.45625,NaN,NaN,cardiopathie congénitale suivie en ambulatoire,PRM2_Antecedant,Emiliane BWANAPONGO LAURE,F,2019/09/01,2019,5,OUI
115,63f7ac1f-54f4-4b24-82c5-f66830a27128,45216.66250,CUSTOM,1.0,cardiopathie congénitale sous contrôle,DIAG_Synd_1,Emiliane BWANAPONGO LAURE,F,2019/09/01,2019,5,OUI
116,ef2bb93b-00d5-4f70-927f-bb4412d985cf,45275.43958,NaN,0.0,"4e d’une fratrie de 4, né prématuré avec 1kg 9...",PRM2_Antecedant,ISILI MANZA VICTORIA,F,2023/11/02,2023,1,OUI
117,ef2bb93b-00d5-4f70-927f-bb4412d985cf,45275.43958,CUSTOM,1.0,bronchiolite aigue du nourrisson sur cardiopat...,DIAG_Synd_1,ISILI MANZA VICTORIA,F,2023/11/02,2023,1,OUI
118,75f4cec5-c3fc-4949-a140-264fa970b1a7,45166.52917,NaN,NaN,suivi pour une cardiopathie sous aldactone,PRM2_Antecedant,MUMBERE KAYIHEMBAKO Gabriel,M,2020/09/20,2020,4,OUI

In [15]:
df.columns

Index(['cEVT_ID', 'cEVT_Date', 'cCHP_VAL_Alpha', 'cCHP_VAL_Num',
       'cCHP_VAL_Memo', 'cCHP_Code', 'NOM COMPLET', 'cPAT_Genre', 'DNN',
       'ANNE', 'AGE', '<= 5ans'],
      dtype='object')

In [16]:
df.head()

,cEVT_ID,cEVT_Date,cCHP_VAL_Alpha,cCHP_VAL_Num,cCHP_VAL_Memo,cCHP_Code,NOM COMPLET,cPAT_Genre,DNN,ANNE,AGE,<= 5ans
0,1445d354-842a-4e34-868b-870115d1ffe1,45096.63206,NaN,NaN,1erF son frère en BSA\ntransfusion + 1x pathol...,PRM2_Antecedant,USHINDI MUBAKE,M,2020/08/27,2020,4,OUI
1,5d53b8de-e964-4077-8093-4af43e947179,45038.45898,NaN,NaN,5eme sur 5 accouche par césarienne pour micros...,PRM2_Antecedant,MIHIYO MUTEBERWA,M,2022/10/25,2022,2,OUI
2,be99614c-e73f-4eee-8915-81394435aa95,45030.50928,NaN,NaN,"Drépanocytaire connu ,suivi à l’HPNK, sous hy...",PRM2_Antecedant,KAOTA KAOMBO micheline,F,2010/11/15,2010,14,NON
3,b19d4859-ff8a-4f98-8399-b61d6ffb75f1,44932.42413,CUSTOM,1.0,myocardiopathie acquise ?,DIAG_Synd_2,MWANZE JOANA,F,2009/10/03,2009,15,NON
4,882ea33e-61b4-4688-80fd-0e8a0dea6757,45077.43109,CUSTOM,1.0,cardiopathie,DIAG_Synd_1,RIZIKI NKUNDWANDIHO LILIANE,F,2012/03/05,2012,12,NON

In [20]:
df.tail

<bound method NDFrame.tail of                                   cEVT_ID    cEVT_Date cCHP_VAL_Alpha  \
0    1445d354-842a-4e34-868b-870115d1ffe1  45096.63206            NaN
1    5d53b8de-e964-4077-8093-4af43e947179  45038.45898            NaN
2    be99614c-e73f-4eee-8915-81394435aa95  45030.50928            NaN
3    b19d4859-ff8a-4f98-8399-b61d6ffb75f1  44932.42413         CUSTOM
4    882ea33e-61b4-4688-80fd-0e8a0dea6757  45077.43109         CUSTOM
..                                    ...          ...            ...
114  737a0c45-e9ea-4a95-8ecd-99d1a5837c07  45227.45625            NaN
115  63f7ac1f-54f4-4b24-82c5-f66830a27128  45216.66250         CUSTOM
116  ef2bb93b-00d5-4f70-927f-bb4412d985cf  45275.43958            NaN
117  ef2bb93b-00d5-4f70-927f-bb4412d985cf  45275.43958         CUSTOM
118  75f4cec5-c3fc-4949-a140-264fa970b1a7  45166.52917            NaN

     cCHP_VAL_Num                                      cCHP_VAL_Memo  \
0             NaN  1erF son frère en BSA\ntransfusion + 1x pathol...
1             NaN  5eme sur 5 accouche par césarienne pour micros...
2             NaN  Drépanocytaire connu  ,suivi à l’HPNK, sous hy...
3             1.0                          myocardiopathie acquise ?
4             1.0                                       cardiopathie
..            ...                                                ...
114           NaN    cardiopathie congénitale suivie en ambulatoire
115           1.0            cardiopathie congénitale sous contrôle
116           0.0  4e d’une fratrie de 4, né prématuré avec 1kg 9...
117           1.0  bronchiolite aigue du nourrisson sur cardiopat...
118           NaN         suivi pour une cardiopathie sous aldactone

           cCHP_Code                    NOM COMPLET cPAT_Genre         DNN  \
0    PRM2_Antecedant                USHINDI MUBAKE           M  2020/08/27
1    PRM2_Antecedant              MIHIYO MUTEBERWA           M  2022/10/25
2    PRM2_Antecedant         KAOTA KAOMBO micheline          F  2010/11/15
3        DIAG_Synd_2                  MWANZE JOANA           F  2009/10/03
4        DIAG_Synd_1    RIZIKI NKUNDWANDIHO LILIANE          F  2012/03/05
..               ...                            ...        ...         ...
114  PRM2_Antecedant      Emiliane BWANAPONGO LAURE          F  2019/09/01
115      DIAG_Synd_1      Emiliane BWANAPONGO LAURE          F  2019/09/01
116  PRM2_Antecedant           ISILI MANZA VICTORIA          F  2023/11/02
117      DIAG_Synd_1           ISILI MANZA VICTORIA          F  2023/11/02
118  PRM2_Antecedant  MUMBERE  KAYIHEMBAKO Gabriel           M  2020/09/20

     ANNE  AGE <= 5ans
0    2020    4     OUI
1    2022    2     OUI
2    2010   14     NON
3    2009   15     NON
4    2012   12     NON
..    ...  ...     ...
114  2019    5     OUI
115  2019    5     OUI
116  2023    1     OUI
117  2023    1     OUI
118  2020    4     OUI

[119 rows x 12 columns]>

In [22]:
df.dtypes

cEVT_ID            object
cEVT_Date         float64
cCHP_VAL_Alpha     object
cCHP_VAL_Num      float64
cCHP_VAL_Memo      object
cCHP_Code          object
NOM COMPLET        object
cPAT_Genre         object
DNN                object
ANNE                int64
AGE                 int64
<= 5ans            object
dtype: object

In [24]:
df.nunique()

cEVT_ID           106
cEVT_Date         106
cCHP_VAL_Alpha      1
cCHP_VAL_Num        2
cCHP_VAL_Memo     105
cCHP_Code           8
NOM COMPLET        87
cPAT_Genre          2
DNN                84
ANNE               19
AGE                19
<= 5ans             2
dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cEVT_ID         119 non-null    object
 1   cEVT_Date       119 non-null    float64
 2   cCHP_VAL_Alpha  63 non-null     object
 3   cCHP_VAL_Num    66 non-null     float64
 4   cCHP_VAL_Memo   119 non-null    object
 5   cCHP_Code       119 non-null    object
 6   NOM COMPLET     119 non-null    object
 7   cPAT_Genre      119 non-null    object
 8   DNN             119 non-null    object
 9   ANNE            119 non-null    int64
 10  AGE             119 non-null    int64
 11  <= 5ans         119 non-null    object
dtypes: float64(2), int64(2), object(8)
memory usage: 11.3+ KB

In [28]:
df.describe()

          cEVT_Date  cCHP_VAL_Num         ANNE         AGE
count    119.000000     66.000000   119.000000  119.000000
mean   45140.739801      0.954545  2017.428571    6.571429
std       98.603453      0.209895     5.516649    5.516649
min    44932.424130      0.000000  2005.000000    1.000000
25%    45074.511645      1.000000  2012.000000    2.000000
50%    45141.488320      1.000000  2020.000000    4.000000
75%    45225.473265      1.000000  2022.000000   12.000000
max    45288.464580      1.000000  2023.000000   19.000000

In [30]:
df.count()

cEVT_ID           119
cEVT_Date         119
cCHP_VAL_Alpha     63
cCHP_VAL_Num       66
cCHP_VAL_Memo     119
cCHP_Code         119
NOM COMPLET       119
cPAT_Genre        119
DNN               119
ANNE              119
AGE               119
<= 5ans           119
dtype: int64

In [32]:
df["cCHP_VAL_Memo"].value_counts()

cardiopathie                                                                                                                                                                                                                                                                               6
cardiopathie                                                                                                                                                                                                                                                                               4
cardiopathie congénitale                                                                                                                                                                                                                                                                   3
cardiopathie congenitale a investiguer                                                                                                                                                                                                                                                     2
exclure une cardiopathie congenitale                                                                                                                                                                                                                                                       2
                                                                                                                                                                                                                                                                                          ..
4eme F4 notion de deces par cardiopathie chez son frère \nnotion d'hospitalisation antérieure-\nCv BCG+\nne par voie basse cri a la naissance \nPN 3100g \ntransfusion-\nutilisation mild+\nallaitement maternel exclusif \n                                                               1
cardiopathie congenitale non cyanogène                                                                                                                                                                                                                                                     1
convulsion aigue febrile sur cardiopathies congeni                                                                                                                                                                                                                                         1
9emeF9 ses frères et soeurs sont en bonne santé apparente \n  hospitalisation recente-\nnotion de cardiopathies congénitale sous Aldactone co 25mg 1co par jour \npas notion d asthme \nCV bien suivi\ndéparasitage il y a 2sem\nMILDA-\nallergies médicaments non connu \ntransfusion-    1
suivi pour une cardiopathie sous aldactone                                                                                                                                                                                                                                                 1
Name: cCHP_VAL_Memo, Length: 105, dtype: int64

In [34]:
df.nunique()

cEVT_ID           106
cEVT_Date         106
cCHP_VAL_Alpha      1
cCHP_VAL_Num        2
cCHP_VAL_Memo     105
cCHP_Code           8
NOM COMPLET        87
cPAT_Genre          2
DNN                84
ANNE               19
AGE                19
<= 5ans             2
dtype: int64